In [1]:
import pandas as pd
from sqlalchemy import create_engine

# NOTES ON THIS VERSION

This version takes a Facebook, Pinterest, and Google ads CSV for the advertisers
It then takes an iOS and Android AppsFlyer CSV for the Installs/down the funnel events

The Facebook file has a column for "campaign name" which always has "IOS" or "ANDROID" in the title and "Evergreen" if it is one of the evergreen campaigns. This allows us to split up the performance by platform as well as by evergreen/non evergreen

# ADVERTISER DATA PREPARATION

### Global Variables

In [2]:
folder_with_csvs = "Resources"
folder_output_csvs = "Output_2019-05-05"

### Extract Advertiser CSVs into DataFrames

In [4]:
facebook_file = folder_with_csvs + "/FACEBOOK.csv"
facebook_df = pd.read_csv(facebook_file)
display(facebook_df.head())

facebook_eg_string = "Facebook Ads EG"
facebook_non_eg_string = "Facebook Ads"

,Day,Campaign Name,Amount Spent (USD),Impressions,Reach,Link Clicks,Link Clicks [On Ad],Unique Link Clicks,Unique Link Clicks [On Ad],Mobile App Installs,Unique Mobile App Tutorials Completed,Unique Mobile App Purchases,Reporting Starts,Reporting Ends
0,2019-05-05,bidalgo_2019_04 | Evergreen CPT with CBO and P...,1171.71,136002,124896,1406.0,1406.0,1397.0,1397.0,601.0,342.0,75.0,2019-05-05,2019-05-05
1,2019-05-05,bidalgo_2019_04_27 | Evergreen CPT with CBO an...,500.84,66278,54112,781.0,781.0,772.0,772.0,289.0,160.0,19.0,2019-05-05,2019-05-05
2,2019-05-05,bidalgo_2018_06 | Launch Ads V1 | iOS | Moms 2...,0.14,24,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-05,2019-05-05
3,2019-05-05,bidalgo_2019_05_04 | CPI TEST Intimacy Ads | I...,204.33,44857,43184,470.0,470.0,469.0,469.0,138.0,84.0,6.0,2019-05-05,2019-05-05
4,2019-05-05,bidalgo_2018_07 | Launch Ads - VIDEO | iOS | M...,9.90,1552,1462,1.0,1.0,1.0,1.0,2.0,2.0,NaN,2019-05-05,2019-05-05

In [5]:
pinterest_file = folder_with_csvs + "/PINTEREST.csv"
pinterest_df = pd.read_csv(pinterest_file)
display(pinterest_df.head())

,Campaign ID,Campaign name,Date,Campaign goal,Ad Format Type,Spend in account currency,Impressions,Clicks,Saves,Closeups,...,Earned Send Unique Users,Downstream Flag Unique Users,Sum of Installs from all Paid activity,Installs resulting from Paid clicks,Installs resulting from views on Paid promotion,Installs resulting from Paid Close Ups & Saves,Sum of Installs from all Earned activity,Installs resulting from Earned clicks,Installs resulting from views on Earned promotions,Installs resulting from Earned Close Ups & Saves
0,C626739958135,iOS - Prospecting - KW,2019-04-06,App_install_traffic,One Tap,198.58,283036.0,1663.0,49.0,16084.0,...,0.0,0,142.0,130.0,8.0,4.0,0.0,0.0,0.0,0.0
1,C626739958135,iOS - Prospecting - KW,2019-04-07,App_install_traffic,One Tap,200.00,271653.0,1660.0,36.0,15923.0,...,0.0,0,164.0,134.0,26.0,4.0,0.0,0.0,0.0,0.0
2,C626739958135,iOS - Prospecting - KW,2019-04-08,App_install_traffic,One Tap,199.59,276760.0,1677.0,37.0,13513.0,...,0.0,0,198.0,175.0,20.0,3.0,2.0,2.0,0.0,0.0
3,C626739958135,iOS - Prospecting - KW,2019-04-09,App_install_traffic,One Tap,100.00,153199.0,839.0,13.0,7811.0,...,0.0,0,96.0,89.0,4.0,3.0,0.0,0.0,0.0,0.0
4,C626739958135,iOS - Prospecting - KW,2019-04-10,App_install_traffic,One Tap,100.00,157408.0,832.0,28.0,7886.0,...,0.0,0,63.0,58.0,3.0,2.0,0.0,0.0,0.0,0.0

In [6]:
google_file = folder_with_csvs + "/GOOGLE.csv"
google_df = pd.read_csv(google_file, skiprows=2)
display(google_df.head())

,Day,Campaign type,Campaign,Currency,Cost,Impressions,Views,Clicks
0,2019-04-24,Universal app,2019_04 | UAC INSTALLS - V1 | IOS | image - ex...,USD,514.63,"95,418","10,756",279
1,2019-04-25,Universal app,2019_04 | UAC INSTALLS - V1 | IOS | image - ex...,USD,506.81,"162,903","13,529",471
2,2019-04-26,Universal app,2019_04 | UAC INSTALLS - V1 | IOS | image - ex...,USD,81.79,"46,785","3,566",137
3,2019-04-27,Universal app,2019_04 | UAC INSTALLS - V1 | IOS | image - ex...,USD,909.81,"596,122","23,035","2,005"
4,2019-04-28,Universal app,2019_04 | UAC INSTALLS - V1 | IOS | image - ex...,USD,112.49,"46,903","2,373",231

In [7]:
# asa_file = folder_with_csvs + "/ASA.csv"
# asa_df = pd.read_csv(asa_file)
# asa_df.head()

asa_basic_string = "ASA Basic"
asa_advanced_string = "ASA Advanced"

### Transform FACEBOOK DataFrame

In [9]:
# Create a filtered dataframe from specific columns
facebook_cols = ["Day", "Campaign Name", "Amount Spent (USD)", 
                 "Impressions", "Reach", "Link Clicks", "Unique Link Clicks"]

facebook_transformed = facebook_df[facebook_cols].copy()

# Rename the column headers
facebook_transformed = facebook_transformed.rename(columns={"Day": "date",
                                                            "Campaign Name": "campaign_name",
                                                            "Amount Spent (USD)": "spend",
                                                            "Impressions": "impressions",                                                     
                                                            "Reach": "impressions_unique",
                                                            "Link Clicks": "clicks",
                                                            "Unique Link Clicks": "clicks_unique"})


# # names for devices in each platform
# device_names_ios = ["ipod","iphone","ipad"]
# device_names_android = ["android_smartphone","android_tablet"]


# # add column to identify which platform (IOS or ANDROID) was being delivered impressions
# facebook_transformed["device_type"] = "other"
# facebook_transformed.loc[facebook_transformed["impression_device"].isin(device_names_ios) ,["device_type"]] = "IOS"
# facebook_transformed.loc[facebook_transformed["impression_device"].isin(device_names_android) ,["device_type"]] = "ANDROID"


facebook_transformed["device_type"] = "other"
facebook_transformed.loc[facebook_transformed['campaign_name'].str.contains('(?i)IOS'),"device_type"] = "IOS"
facebook_transformed.loc[facebook_transformed['campaign_name'].str.contains('(?i)ANDROID'),"device_type"] = "ANDROID"

facebook_transformed["advertiser"] = facebook_non_eg_string
facebook_transformed.loc[facebook_transformed['campaign_name'].str.contains('(?i)Evergreen'),"advertiser"] = facebook_eg_string


# facebook_spend_reach_by_device_type = facebook_transformed.groupby(["date","device_type"]).sum()
facebook_spend_reach_by_device_type = facebook_transformed.groupby(["date","device_type", "advertiser"],as_index=False).sum()

facebook_spend_reach_by_device_type_final = facebook_spend_reach_by_device_type.loc[facebook_spend_reach_by_device_type["device_type"] != "other", :]

# display(facebook_spend_reach_by_device_type_final.head())



# add the AppsFlyer advertiser name and Split out IOS and ANDROID into separate dataframes
# facebook_spend_reach_by_device_type_final["advertiser"] = facebook_non_eg_string

facebook_spend_reach_clicks_ios = facebook_spend_reach_by_device_type_final.loc[facebook_spend_reach_by_device_type_final["device_type"] == "IOS",:]
facebook_spend_reach_clicks_android = facebook_spend_reach_by_device_type_final.loc[facebook_spend_reach_by_device_type_final["device_type"] == "ANDROID",:]

# pinterest_spend_reach_clicks_android = 


display(facebook_spend_reach_clicks_ios.head())
display(facebook_spend_reach_clicks_android.tail())

,date,device_type,advertiser,spend,impressions,impressions_unique,clicks,clicks_unique
1,2019-04-06,IOS,Facebook Ads,489.48,115877,112233,826.0,822.0
2,2019-04-06,IOS,Facebook Ads EG,497.64,85205,82800,772.0,766.0
4,2019-04-07,IOS,Facebook Ads,439.67,104646,101376,640.0,637.0
5,2019-04-07,IOS,Facebook Ads EG,500.40,91179,89453,794.0,788.0
7,2019-04-08,IOS,Facebook Ads,379.69,89908,88666,473.0,470.0

,date,device_type,advertiser,spend,impressions,impressions_unique,clicks,clicks_unique
87,2019-05-03,ANDROID,Facebook Ads,367.06,55099,46112,367.0,363.0
88,2019-05-03,ANDROID,Facebook Ads EG,500.22,50496,40454,516.0,514.0
91,2019-05-04,ANDROID,Facebook Ads,109.88,16523,14355,114.0,114.0
92,2019-05-04,ANDROID,Facebook Ads EG,497.68,63057,48960,588.0,585.0
95,2019-05-05,ANDROID,Facebook Ads EG,500.84,66278,54112,781.0,772.0

### Transform PINTEREST DataFrame

In [10]:
pinterest_cols = ["Campaign ID", "Campaign name", "Date", "Spend in account currency", 
                  "Impressions", "Impression Unique Users", "Clicks", "Click Unique Users"]

pinterest_transformed = pinterest_df[pinterest_cols].copy()

# Rename the column headers
pinterest_transformed = pinterest_transformed.rename(columns={"Campaign ID": "campaign_id",
                                                         "Campaign name": "campaign_name",
                                                         "Date": "date",
                                                         "Spend in account currency": "spend",
                                                         "Impressions": "impressions",
                                                         "Impression Unique Users": "impressions_unique",
                                                         "Clicks": "clicks",
                                                         "Click Unique Users": "clicks_unique"})

pinterest_transformed["device_type"] = "other"
pinterest_transformed.loc[pinterest_transformed['campaign_name'].str.contains('(?i)IOS'),"device_type"] = "IOS"
pinterest_transformed.loc[pinterest_transformed['campaign_name'].str.contains('(?i)ANDROID'),"device_type"] = "ANDROID"


pinterest_spend_reach_by_device_type = pinterest_transformed.groupby(["date","device_type"],as_index=False).sum()

pinterest_spend_reach_by_device_type_final = pinterest_spend_reach_by_device_type.loc[pinterest_spend_reach_by_device_type["device_type"] != "other", :]

pinterest_spend_reach_by_device_type_final.head(10)



# add the AppsFlyer advertiser name and Split out IOS and ANDROID into separate dataframes
pinterest_spend_reach_by_device_type_final["advertiser"] = "pinterest_int"

pinterest_spend_reach_clicks_ios = pinterest_spend_reach_by_device_type_final.loc[pinterest_spend_reach_by_device_type_final["device_type"] == "IOS",:]
pinterest_spend_reach_clicks_android = pinterest_spend_reach_by_device_type_final.loc[pinterest_spend_reach_by_device_type_final["device_type"] == "ANDROID",:]

# pinterest_spend_reach_clicks_android = 


display(pinterest_spend_reach_clicks_ios.head())
display(pinterest_spend_reach_clicks_android.head())

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,date,device_type,spend,impressions,impressions_unique,clicks,clicks_unique,advertiser
1,2019-04-06,IOS,652.34,744777.0,477859.0,4290.0,4196.0,pinterest_int
4,2019-04-07,IOS,724.14,778950.0,507270.0,4645.0,4529.0,pinterest_int
7,2019-04-08,IOS,829.15,850544.0,571909.0,5363.0,5238.0,pinterest_int
10,2019-04-09,IOS,672.04,758350.0,538871.0,4582.0,4513.0,pinterest_int
13,2019-04-10,IOS,644.11,671085.0,450678.0,4125.0,4058.0,pinterest_int

,date,device_type,spend,impressions,impressions_unique,clicks,clicks_unique,advertiser
0,2019-04-06,ANDROID,150.00,162507.0,101204.0,1107.0,1092.0,pinterest_int
3,2019-04-07,ANDROID,149.65,171508.0,105752.0,1128.0,1117.0,pinterest_int
6,2019-04-08,ANDROID,149.40,159137.0,100565.0,1129.0,1110.0,pinterest_int
9,2019-04-09,ANDROID,150.00,171746.0,106958.0,1125.0,1111.0,pinterest_int
12,2019-04-10,ANDROID,149.88,160629.0,101394.0,1114.0,1105.0,pinterest_int

### Transform GOOGLE ADS DataFrame

In [11]:
# Create a filtered dataframe from specific columns
google_cols = ["Day", "Campaign", "Cost", 
                 "Impressions", "Views", "Clicks"]

google_transformed = google_df[google_cols].copy()

# Rename the column headers
google_transformed = google_transformed.rename(columns={"Day": "date",
                                                            "Campaign": "campaign_name",
                                                            "Cost": "spend",
                                                            "Impressions": "impressions",                                                     
                                                            "Views": "views",
                                                            "Clicks": "clicks"})

# display(google_transformed["spend"].dtypes)

google_transformed["impressions"] = google_transformed["impressions"].str.replace(",","").astype(int)
google_transformed["views"] = google_transformed["views"].str.replace(",","").astype(int)
google_transformed["clicks"] = google_transformed["clicks"].str.replace(",","").astype(int)

# pd.to_numeric(s, errors='ignore')

# pinterest_transformed["device_type"] = "other"
# pinterest_transformed.loc[pinterest_transformed['campaign_name'].str.contains('(?i)IOS'),"device_type"] = "IOS"
# pinterest_transformed.loc[pinterest_transformed['campaign_name'].str.contains('(?i)ANDROID'),"device_type"] = "ANDROID"


google_transformed["device_type"] = "IOS"

google_spend_reach_by_device_type = google_transformed.groupby(["date","device_type"],as_index=False).sum()

google_spend_reach_by_device_type_final = google_spend_reach_by_device_type.loc[google_spend_reach_by_device_type["device_type"] != "other", :]

# display(google_spend_reach_by_device_type_final.head())



# add the AppsFlyer advertiser name and Split out IOS and ANDROID into separate dataframes
google_spend_reach_by_device_type_final["advertiser"] = "googleadwords_int"


google_spend_reach_clicks_ios = google_spend_reach_by_device_type_final.loc[google_spend_reach_by_device_type_final["device_type"] == "IOS",:]
google_spend_reach_clicks_android = google_spend_reach_by_device_type_final.loc[google_spend_reach_by_device_type_final["device_type"] == "ANDROID",:]

display(google_spend_reach_clicks_ios.head())
display(google_spend_reach_clicks_android.tail())

dtype('float64')

         date device_type   spend  impressions  views  clicks
0  2019-04-24         IOS  514.63        95418  10756     279
1  2019-04-25         IOS  506.81       162903  13529     471
2  2019-04-26         IOS   81.79        46785   3566     137
3  2019-04-27         IOS  909.81       596122  23035    2005
4  2019-04-28         IOS  112.49        46903   2373     231

,date,device_type,spend,impressions,views,clicks,advertiser
0,2019-04-24,IOS,514.63,95418,10756,279,googleadwords_int
1,2019-04-25,IOS,506.81,162903,13529,471,googleadwords_int
2,2019-04-26,IOS,81.79,46785,3566,137,googleadwords_int
3,2019-04-27,IOS,909.81,596122,23035,2005,googleadwords_int
4,2019-04-28,IOS,112.49,46903,2373,231,googleadwords_int

Empty DataFrame
Columns: [date, device_type, spend, impressions, views, clicks, advertiser]
Index: []

In [ ]:
# google_transformed["impressions"] = google_transformed["impressions"].str.replace(",","").astype(int)
# google_transformed["views"] = google_transformed["views"].str.replace(",","").astype(int)
# google_transformed["clicks"] = google_transformed["clicks"].str.replace(",","").astype(int)
# # google_transformed[["impressions", "views"]] = google_transformed[["impressions", "views"]].apply(pd.to_numeric)


# google_transformed.head()

# APPSFLYER DATA PREPARATION

### Extract APPSFLYER CSVs into DataFrames

In [12]:
appsflyer_ios_file = folder_with_csvs + "/APPSFLYER-IOS.csv"
appsflyer_ios_df = pd.read_csv(appsflyer_ios_file)
display(appsflyer_ios_df.head(100))

,Date,Agency/PMD (af_prt),Media Source (pid),Campaign (c),Impressions,Clicks,CTR,Installs,Conversion Rate,Sessions,...,ltv_20190501 (Sales in USD),ltv_20190504 (Unique users),ltv_20190504 (Event counter),ltv_20190504 (Sales in USD),ltv_20190505 (Unique users),ltv_20190505 (Event counter),ltv_20190505 (Sales in USD),new_workout_saved (Unique users),new_workout_saved (Event counter),new_workout_saved (Sales in USD)
0,2019-04-06,None,Apple Search Ads,Moov Studio: Fitness Workouts - 1274153663,NaN,NaN,NaN,40,NaN,126,...,0.00,0,0,0.00000,0,0,0.00000,32,44,0.0
1,2019-04-06,None,Apple Search Ads,Performance - Brand,104.0,6.0,0.0577,2,0.3333,5,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
2,2019-04-06,None,Apple Search Ads,Performance - Competitor,225.0,14.0,0.0622,6,0.4286,13,...,0.00,0,0,0.00000,0,0,0.00000,1,1,0.0
3,2019-04-06,None,Apple Search Ads,Performance - Generic,139.0,16.0,0.1151,8,0.5000,26,...,59.99,1,1,59.99000,1,1,59.99000,6,9,0.0
4,2019-04-06,None,Deep Linking,Deep Link Redirect iOS,NaN,16.0,NaN,0,0.0000,0,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
5,2019-04-06,None,Facebook Ads,2018_06 | Launch Ads V1 | iOS | Moms 25-39 | 4...,673.0,8.0,0.0119,1,0.1250,1,...,0.00,0,0,0.00000,0,0,0.00000,1,1,0.0
6,2019-04-06,None,Facebook Ads,2018_07 | Launch Ads - VIDEO | iOS | Moms 25-3...,1005.0,4.0,0.0040,3,0.7500,12,...,0.00,0,0,0.00000,0,0,0.00000,2,2,0.0
7,2019-04-06,None,Facebook Ads,2019_02 | Trial Start Optimized Delivery with ...,1.0,NaN,NaN,0,NaN,0,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
8,2019-04-06,None,Facebook Ads,2019_03 | TEST Campaign | iOS | Multiple Audie...,70706.0,580.0,0.0082,224,0.3862,611,...,59.99,1,1,59.99000,1,1,59.99000,124,195,0.0
9,2019-04-06,None,Facebook Ads,2019_03 | Trial Start Optimized Delivery with ...,145855.0,1342.0,0.0092,358,0.2668,1296,...,779.82,18,18,779.82000,18,18,779.82000,206,643,0.0
10,2019-04-06,None,Facebook Ads,2019_04 | CPI TEST Dating the wrong guys | IOS...,13911.0,106.0,0.0076,29,0.2736,85,...,19.98,2,2,19.98000,2,2,19.98000,16,19,0.0
11,2019-04-06,None,Facebook Ads,2019_04 | CPI TEST I have no boundaries | IOS ...,14917.0,62.0,0.0042,18,0.2903,52,...,0.00,0,0,0.00000,0,0,0.00000,8,8,0.0
12,2019-04-06,None,Facebook Ads,2019_04 | CPI TEST Something is wrong with me ...,14552.0,66.0,0.0045,22,0.3333,121,...,0.00,0,0,0.00000,0,0,0.00000,20,135,0.0
13,2019-04-06,None,Facebook Ads,2019_04 | Evergreen CPT with CBO and PPP | IOS...,85157.0,772.0,0.0091,0,0.0000,0,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
14,2019-04-06,None,Organic,None,NaN,NaN,NaN,709,NaN,0,...,0.00,0,0,0.00000,0,0,0.00000,345,654,0.0
15,2019-04-06,None,SocialInstagram,InstagramBioUniv,NaN,57.0,NaN,1,0.0175,3,...,0.00,0,0,0.00000,0,0,0.00000,1,1,0.0
16,2019-04-06,None,Website,Bottom of Page iOS Download Link,NaN,10.0,NaN,4,0.4000,9,...,0.00,0,0,0.00000,0,0,0.00000,4,4,0.0
17,2019-04-06,None,Website,FAQ iOS Link,NaN,1.0,NaN,0,0.0000,0,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
18,2019-04-06,None,Website,Navigation Bar App Download Button Both Platforms,NaN,12.0,NaN,5,0.4167,15,...,0.00,0,0,0.00000,0,0,0.00000,5,8,0.0
19,2019-04-06,None,pinterest_int,2019_01 | AAL | iOS,32958.0,166.0,0.0050,25,0.1506,109,...,119.98,2,2,119.98000,2,2,119.98000,12,31,0.0
20,2019-04-06,None,pinterest_int,2019_01 | Interests | iOS,164441.0,1129.0,0.0069,218,0.1931,667,...,129.97,3,3,129.97000,3,3,129.97000,130,225,0.0
21,2019-04-06,None,pinterest_int,2019_02 | Interests | iOS | Lifestyle Ads,70627.0,300.0,0.0042,12,0.0400,35,...,0.00,0,0,0.00000,0,0,0.00000,7,9,0.0
22,2019-04-06,None,pinterest_int,iOS - Prospecting - KW,285749.0,1727.0,0.0060,142,0.0822,417,...,179.97,3,3,179.97000,3,3,179.97000,96,185,0.0
23,2019-04-06,None,pinterest_int,iOS - Prospecting - KW - CPI,165144.0,999.0,0.0060,201,0.2012,567,...,79.97,3,3,79.97000,3,3,79.97000,120,201,0.0
24,2019-04-07,None,Apple Search Ads,Moov Studio: Fitness Workouts - 1274153663,NaN,NaN,NaN,48,NaN,157,...,59.99,1,1,59.99000,1,1,59.99000,30,64,0.0
25,2019-04-07,None,Apple Search Ads,Performance - Brand,115.0,4.0,0.0348,2,0.5000,5,...,0.00,0,0,0.00000,0,0,0.00000,1,1,0.0
26,2019-04-07,None,Apple Search Ads,Performance - Competitor,496.0,22.0,0.0444,9,0.4091,22,...,0.00,0,0,0.00000,0,0,0.00000,7,8,0.0
27,2019-04-07,None,Apple Search Ads,Performance - Generic,146.0,25.0,0.1712,14,0.5600,35,...,0.00,0,0,0.00000,0,0,0.00000,8,10,0.0
28,2019-04-07,None,Deep Linking,Deep Link Redirect iOS,NaN,39.0,NaN,1,0.0256,1,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
29,2019-04-07,None,Facebook Ads,2018_06 | Launch Ads V1 | iOS | Moms 25-39 | 4...,1455.0,22.0,0.0151,10,0.4545,24,...,0.00,0,0,0.00000,0,0,0.00000,4,4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2019-04-08,None,pinterest_int,2019_02 | Interests | iOS | Lifestyle Ads,28573.0,135.0,0.0047,10,0.0741,23,...,0.00,0,0,0.00000,0,0,0.00000,5,5,0.0
71,2019-04-08,None,pinterest_int,iOS - Prospecting - KW,168910.0,945.0,0.0056,116,0.1228,388,...,189.96,5,5,199.95001,5,5,199.95001,75,194,0.0
72,2019-04-08,None,pinterest_int,iOS - Prospecting - KW - CPI,437145.0,2525.0,0.0058,403,0.1596,1199,...,429.92,8,8,429.92000,8,8,429.92000,266,560,0.0
73,2019-04-09,None,Apple Search Ads,Moov Studio: Fitness Workouts - 1274153663,NaN,NaN,NaN,54,NaN,190,...,0.00,0,0,0.00000,0,0,0.00000,33,43,0.0
74,2019-04-09,None,Apple Search Ads,Performance - Brand,102.0,5.0,0.0490,4,0.8000,21,...,59.99,1,1,59.99000,1,1,59.99000,1,12,0.0
75,2019-04-09,None,Apple Search Ads,Performance - Competitor,636.0,42.0,0.0660,13,0.3095,41,...,59.99,1,1,59.99000,1,1,59.99000,7,9,0.0
76,2019-04-09,None,Apple Search Ads,Performance - Generic,155.0,29.0,0.1871,10,0.3448,31,...,0.00,0,0,0.00000,0,0,0.00000,6,7,0.0
77,2019-04-09,None,Deep Linking,Deep Link Redirect iOS,NaN,17.0,NaN,1,0.0588,3,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
78,2019-04-09,None,Facebook Ads,2018_06 | Launch Ads V1 | iOS | Moms 25-39 | 4...,1143.0,13.0,0.0114,8,0.6154,18,...,0.00,0,0,0.00000,0,0,0.00000,1,1,0.0
79,2019-04-09,None,Facebook Ads,2018_07 | Launch Ads - VIDEO | iOS | Moms 25-3...,1065.0,2.0,0.0019,1,0.5000,2,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
80,2019-04-09,None,Facebook Ads,2019_03 | TEST Campaign | iOS | Multiple Audie...,NaN,NaN,NaN,11,NaN,26,...,0.00,0,0,0.00000,0,0,0.00000,5,6,0.0
81,2019-04-09,None,Facebook Ads,2019_03 | Trial Start Optimized Delivery with ...,143693.0,1385.0,0.0096,377,0.2722,1259,...,721.82,18,18,721.82000,18,18,721.82000,226,566,0.0
82,2019-04-09,None,Facebook Ads,2019_04 | CPI TEST Dating the wrong guys | IOS...,24009.0,104.0,0.0043,37,0.3558,102,...,0.00,0,0,0.00000,0,0,0.00000,22,24,0.0
83,2019-04-09,None,Facebook Ads,2019_04 | CPI TEST I have no boundaries | IOS ...,25749.0,116.0,0.0045,33,0.2845,92,...,0.00,0,0,0.00000,0,0,0.00000,18,25,0.0
84,2019-04-09,None,Facebook Ads,2019_04 | CPI TEST Something is wrong with me ...,23799.0,164.0,0.0069,48,0.2927,155,...,69.98,2,2,69.98000,2,2,69.98000,27,84,0.0
85,2019-04-09,None,Facebook Ads,2019_04 | Evergreen CPT with CBO and PPP | IOS...,77698.0,746.0,0.0096,0,0.0000,0,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
86,2019-04-09,None,Organic,None,NaN,NaN,NaN,753,NaN,0,...,0.00,0,0,0.00000,0,0,0.00000,407,1029,0.0
87,2019-04-09,None,SocialInstagram,InstagramBioUniv,NaN,60.0,NaN,0,0.0000,0,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
88,2019-04-09,None,Website,Bottom of Page iOS Download Link,NaN,16.0,NaN,8,0.5000,21,...,0.00,0,0,0.00000,0,0,0.00000,4,4,0.0
89,2019-04-09,None,Website,FAQ iOS Link,NaN,1.0,NaN,0,0.0000,0,...,0.00,0,0,0.00000,0,0,0.00000,0,0,0.0
90,2019-04-09,None,Website,Navigation Bar App Download Button Both Platforms,NaN,12.0,NaN,4,0.3333,19,...,59.99,1,1,59.99000,1,1,59.99000,2,10,0.0
91,2019-04-09,None,pinterest_int,2019_01 | AAL | iOS,11250.0,59.0,0.0052,15,0.2542,38,...,0.00,0,0,0.00000,0,0,0.00000,10,11,0.0
92,2019-04-09,None,pinterest_int,2019_01 | Interests | iOS,225043.0,1562.0,0.0069,351,0.2247,1068,...,89.96,4,4,89.96000,4,4,89.96000,218,418,0.0
93,2019-04-09,None,pinterest_int,2019_02 | Interests | iOS | Lifestyle Ads,11608.0,55.0,0.0047,2,0.0364,3,...,0.00,0,0,0.00000,0,0,0.00000,1,1,0.0
94,2019-04-09,None,pinterest_int,iOS - Prospecting - KW,157906.0,833.0,0.0053,76,0.0912,223,...,119.98,2,2,119.98000,2,2,119.98000,41,65,0.0
95,2019-04-09,None,pinterest_int,iOS - Prospecting - KW - CPI,281968.0,1740.0,0.0062,303,0.1741,798,...,119.98,2,2,119.98000,2,2,119.98000,175,236,0.0
96,2019-04-10,None,Apple Search Ads,Moov Studio: Fitness Workouts - 1274153663,NaN,NaN,NaN,55,NaN,145,...,69.98,2,2,69.98000,2,2,69.98000,33,38,0.0
97,2019-04-10,None,Apple Search Ads,Performance - Brand,102.0,3.0,0.0294,2,0.6667,4,...,0.00,0,0,0.00000,0,0,0.00000,1,1,0.0
98,2019-04-10,None,Apple Search Ads,Performance - Competitor,676.0,48.0,0.0710,12,0.2500,34,...,0.00,0,0,0.00000,0,0,0.00000,7,7,0.0
99,2019-04-10,None,Apple Search Ads,Performance - Generic,164.0,21.0,0.1280,8,0.3810,22,...,0.00,0,0,0.00000,0,0,0.00000,7,15,0.0

In [13]:
appsflyer_android_file = folder_with_csvs + "/APPSFLYER-ANDROID.csv"
appsflyer_android_df = pd.read_csv(appsflyer_android_file)
display(appsflyer_android_df.head())

,Date,Agency/PMD (af_prt),Media Source (pid),Campaign (c),Impressions,Clicks,CTR,Installs,Conversion Rate,Sessions,...,ltv_20190501 (Sales in USD),ltv_20190504 (Unique users),ltv_20190504 (Event counter),ltv_20190504 (Sales in USD),ltv_20190505 (Unique users),ltv_20190505 (Event counter),ltv_20190505 (Sales in USD),new_workout_saved (Unique users),new_workout_saved (Event counter),new_workout_saved (Sales in USD)
0,2019-04-06,None,Facebook Ads,2019_02 | Trial Start Optimized Delivery with ...,65574.0,1065.0,0.0162,398,0.3737,1992,...,139.96,3,3,139.96,4,4,199.95001,216,331,0.0
1,2019-04-06,None,Organic,None,NaN,NaN,NaN,124,NaN,0,...,0.00,0,0,0.00,0,0,0.00000,63,192,0.0
2,2019-04-06,None,SocialInstagram,InstagramBioUniv,NaN,34.0,NaN,17,0.5000,65,...,0.00,0,0,0.00,0,0,0.00000,13,17,0.0
3,2019-04-06,None,Website,Bottom of Page Android Download Link,NaN,5.0,NaN,1,0.2000,5,...,0.00,0,0,0.00,0,0,0.00000,1,1,0.0
4,2019-04-06,None,Website,FAQ Android Link,NaN,1.0,NaN,0,0.0000,0,...,0.00,0,0,0.00,0,0,0.00000,0,0,0.0

### SETUP VARIABLES TO USE FOR APPSFLYER IOS/ANDROID DataFrame Transformations

In [14]:
most_recent_ltv_column_prefix = "ltv_20190504"
paid_acquisition_advertisers = [facebook_non_eg_string, facebook_eg_string, "pinterest_int", "googleadwords_int", asa_basic_string, asa_advanced_string, "Organic"]


appsflyer_cols = ["Date", "Media Source (pid)", "Campaign (c)", "Installs", "Sessions", 
                      "new_workout_saved (Unique users)", 
                      "af_purchase (Unique users)",
                      "af_purchase (Event counter)", 
                      "af_start_trial (Unique users)", 
                      "af_start_trial (Event counter)",
                      most_recent_ltv_column_prefix + " (Unique users)",
                      most_recent_ltv_column_prefix + " (Event counter)",
                      most_recent_ltv_column_prefix + " (Sales in USD)"]

### Transform APPSFLYER IOS DataFrame

In [15]:
appsflyer_ios_transformed = appsflyer_ios_df[appsflyer_cols].copy()

# Rename the column headers
appsflyer_ios_transformed = appsflyer_ios_transformed.rename(columns={"Date": "date",
                                                         "Media Source (pid)": "advertiser",
                                                         "Campaign (c)": "campaign_name",
                                                         "Installs": "installs",
                                                         "Sessions": "sessions",
                                                         "new_workout_saved (Unique users)": "new_workout_saved_unique",
                                                         "af_purchase (Unique users)": "af_purchase_unique",
                                                         "af_purchase (Event counter)": "af_purchase_all",
                                                         "af_start_trial (Unique users)": "af_start_trial_unique",
                                                         "af_start_trial (Event counter)": "af_start_trial_all",
                                                         most_recent_ltv_column_prefix + " (Unique users)": "ltv_subs_unique",
                                                         most_recent_ltv_column_prefix + " (Event counter)": "ltv_subs_all",
                                                         most_recent_ltv_column_prefix + " (Sales in USD)": "ltv_subs_revenue"})


# appsflyer_ios_transformed.loc[appsflyer_ios_transformed['campaign_name'].str.contains('(?i)Evergreen'),"advertiser"] = facebook_eg_string

appsflyer_ios_transformed.loc[(appsflyer_ios_transformed['advertiser'] == facebook_non_eg_string)
                              &
                              (appsflyer_ios_transformed['campaign_name'].str.contains('(?i)Evergreen')), "advertiser"] = facebook_eg_string


appsflyer_ios_transformed.loc[(appsflyer_ios_transformed['advertiser'] == "Apple Search Ads")
                              &
                              (appsflyer_ios_transformed['campaign_name'].str.contains('1274153663')), "advertiser"] = asa_basic_string


appsflyer_ios_transformed.loc[appsflyer_ios_transformed['advertiser'] == "Apple Search Ads", "advertiser"] = asa_advanced_string


appsflyer_ios_transformed.insert(10, "trial_starts_unique", appsflyer_ios_transformed["af_purchase_unique"] + appsflyer_ios_transformed["af_start_trial_unique"]) 
appsflyer_ios_transformed.insert(11, "trial_starts_all", appsflyer_ios_transformed["af_purchase_all"] + appsflyer_ios_transformed["af_start_trial_all"]) 

# appsflyer_ios_transformed["trial_starts_total_unique"] = appsflyer_ios_transformed["af_purchase_unique"] + appsflyer_ios_transformed["af_start_trial_unique"]
# appsflyer_ios_transformed["trial_starts_total_all"] = appsflyer_ios_transformed["af_purchase_all"] + appsflyer_ios_transformed["af_start_trial_all"]

appsflyer_ios_grouped = appsflyer_ios_transformed.groupby(["date","advertiser"],as_index=False).sum()

appsflyer_ios_grouped_final = appsflyer_ios_grouped.loc[appsflyer_ios_grouped["advertiser"].isin(paid_acquisition_advertisers), :]

appsflyer_ios_grouped_final.head(200)

,date,advertiser,installs,sessions,new_workout_saved_unique,af_purchase_unique,af_purchase_all,af_start_trial_unique,af_start_trial_all,trial_starts_unique,trial_starts_all,ltv_subs_unique,ltv_subs_all,ltv_subs_revenue
0,2019-04-06,ASA Advanced,16,44,7,1,1,0,0,1,1,1,1,59.99000
1,2019-04-06,ASA Basic,40,126,32,0,0,0,0,0,0,0,0,0.00000
3,2019-04-06,Facebook Ads,655,2178,377,51,51,0,0,51,51,21,21,859.79000
4,2019-04-06,Facebook Ads EG,0,0,0,0,0,0,0,0,0,0,0,0.00000
5,2019-04-06,Organic,709,0,345,27,31,0,0,27,31,0,0,0.00000
8,2019-04-06,pinterest_int,598,1795,365,26,26,1,1,27,27,11,11,509.89000
9,2019-04-07,ASA Advanced,25,62,16,1,1,0,0,1,1,0,0,0.00000
10,2019-04-07,ASA Basic,48,157,30,4,4,0,0,4,4,1,1,59.99000
12,2019-04-07,Facebook Ads,668,2305,373,57,58,0,0,57,58,26,26,1059.74004
13,2019-04-07,Facebook Ads EG,0,0,0,0,0,0,0,0,0,0,0,0.00000
14,2019-04-07,Organic,1239,0,707,47,51,1,1,48,52,0,0,0.00000
18,2019-04-07,pinterest_int,429,1288,251,15,15,0,0,15,15,8,8,221.92000
19,2019-04-08,ASA Advanced,20,68,9,1,1,0,0,1,1,0,0,0.00000
20,2019-04-08,ASA Basic,48,118,25,2,2,0,0,2,2,0,0,0.00000
22,2019-04-08,Facebook Ads,528,1725,300,61,61,0,0,61,61,21,21,713.77000
23,2019-04-08,Facebook Ads EG,0,0,0,0,0,0,0,0,0,0,0,0.00000
24,2019-04-08,Organic,938,0,510,34,36,1,1,35,37,0,0,0.00000
28,2019-04-08,pinterest_int,920,2930,580,51,52,1,1,52,53,28,28,1229.72005
29,2019-04-09,ASA Advanced,27,93,14,3,3,0,0,3,3,2,2,119.98000
30,2019-04-09,ASA Basic,54,190,33,0,0,0,0,0,0,0,0,0.00000
32,2019-04-09,Facebook Ads,515,1654,299,42,43,1,1,43,44,20,20,791.80000
33,2019-04-09,Facebook Ads EG,0,0,0,0,0,0,0,0,0,0,0,0.00000
34,2019-04-09,Organic,753,0,407,40,43,2,2,42,45,0,0,0.00000
37,2019-04-09,pinterest_int,747,2130,445,27,27,1,1,28,28,8,8,329.92000
38,2019-04-10,ASA Advanced,22,60,15,1,1,0,0,1,1,0,0,0.00000
39,2019-04-10,ASA Basic,55,145,33,4,4,0,0,4,4,2,2,69.98000
41,2019-04-10,Facebook Ads,271,896,149,23,23,0,0,23,23,10,10,349.90000
42,2019-04-10,Facebook Ads EG,206,677,123,18,18,0,0,18,18,9,9,339.91000
43,2019-04-10,Organic,766,0,390,34,35,0,0,34,35,0,0,0.00000
46,2019-04-10,pinterest_int,697,2196,429,42,42,0,0,42,42,22,22,1019.78000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,2019-05-01,googleadwords_int,217,607,112,0,0,5,5,5,5,0,0,0.00000
268,2019-05-01,pinterest_int,1245,3637,749,0,0,86,86,86,86,0,0,0.00000
269,2019-05-02,ASA Advanced,17,44,9,0,0,1,1,1,1,0,0,0.00000
270,2019-05-02,ASA Basic,46,138,28,0,0,3,3,3,3,0,0,0.00000
272,2019-05-02,Facebook Ads,98,276,52,0,0,9,9,9,9,0,0,0.00000
273,2019-05-02,Facebook Ads EG,393,1181,240,0,0,46,46,46,46,0,0,0.00000
274,2019-05-02,Organic,957,0,488,0,0,58,60,58,60,0,0,0.00000
277,2019-05-02,googleadwords_int,254,709,143,0,0,13,13,13,13,0,0,0.00000
278,2019-05-02,pinterest_int,1111,3148,638,1,1,75,75,76,76,0,0,0.00000
279,2019-05-03,ASA Advanced,15,41,7,0,0,1,1,1,1,0,0,0.00000
280,2019-05-03,ASA Basic,38,131,19,0,0,5,5,5,5,0,0,0.00000
282,2019-05-03,Facebook Ads,86,232,43,0,0,3,3,3,3,0,0,0.00000
283,2019-05-03,Facebook Ads EG,330,887,196,0,0,40,40,40,40,0,0,0.00000
284,2019-05-03,Organic,799,0,405,0,0,44,46,44,46,0,0,0.00000
288,2019-05-03,googleadwords_int,232,633,127,0,0,8,8,8,8,0,0,0.00000
289,2019-05-03,pinterest_int,896,2420,509,0,0,50,50,50,50,0,0,0.00000
290,2019-05-04,ASA Advanced,4,12,2,0,0,0,0,0,0,0,0,0.00000
291,2019-05-04,ASA Basic,35,113,15,0,0,2,2,2,2,0,0,0.00000
293,2019-05-04,Facebook Ads,67,189,39,0,0,6,6,6,6,0,0,0.00000
294,2019-05-04,Facebook Ads EG,392,1049,236,0,0,49,49,49,49,0,0,0.00000
295,2019-05-04,Organic,922,0,471,0,0,38,40,38,40,0,0,0.00000
298,2019-05-04,googleadwords_int,154,383,73,0,0,2,2,2,2,0,0,0.00000
299,2019-05-04,pinterest_int,1060,2699,628,0,0,43,43,43,43,0,0,0.00000
300,2019-05-05,ASA Advanced,14,31,10,0,0,1,1,1,1,0,0,0.00000
301,2019-05-05,ASA Basic,83,216,54,0,0,4,4,4,4,0,0,0.00000
303,2019-05-05,Facebook Ads,130,311,70,0,0,8,8,8,8,0,0,0.00000
304,2019-05-05,Facebook Ads EG,558,1430,317,0,0,64,64,64,64,0,0,0.00000
305,2019-05-05,Organic,1145,0,629,1,1,65,68,66,69,0,0,0.00000
309,2019-05-05,googleadwords_int,54,115,19,0,0,0,0,0,0,0,0,0.00000
310,2019-05-05,pinterest_int,1203,3026,693,0,0,67,67,67,67,0,0,0.00000

In [ ]:
# organic_spend_reach_clicks_ios = appsflyer_ios_grouped_final.loc[appsflyer_ios_grouped_final['advertiser'] == "Organic", ["date", "advertiser"]]
# organic_spend_reach_clicks_ios["device_type"] = "IOS"
# organic_spend_reach_clicks_ios.head()

### Transform APPSFLYER ANDROID DataFrame

In [16]:
appsflyer_android_transformed = appsflyer_android_df[appsflyer_cols].copy()

# Rename the column headers
appsflyer_android_transformed = appsflyer_android_transformed.rename(columns={"Date": "date",
                                                         "Media Source (pid)": "advertiser",
                                                         "Campaign (c)": "campaign_name",
                                                         "Installs": "installs",
                                                         "Sessions": "sessions",
                                                         "new_workout_saved (Unique users)": "new_workout_saved_unique",
                                                         "af_purchase (Unique users)": "af_purchase_unique",
                                                         "af_purchase (Event counter)": "af_purchase_all",
                                                         "af_start_trial (Unique users)": "af_start_trial_unique",
                                                         "af_start_trial (Event counter)": "af_start_trial_all",
                                                         most_recent_ltv_column_prefix + " (Unique users)": "ltv_subs_unique",
                                                         most_recent_ltv_column_prefix + " (Event counter)": "ltv_subs_all",
                                                         most_recent_ltv_column_prefix + " (Sales in USD)": "ltv_subs_revenue"})


appsflyer_android_transformed.loc[appsflyer_android_transformed['campaign_name'].str.contains('(?i)Evergreen'),"advertiser"] = facebook_eg_string

appsflyer_android_transformed.insert(10, "trial_starts_unique", appsflyer_android_transformed["af_purchase_unique"] + appsflyer_android_transformed["af_start_trial_unique"]) 
appsflyer_android_transformed.insert(11, "trial_starts_all", appsflyer_android_transformed["af_purchase_all"] + appsflyer_android_transformed["af_start_trial_all"]) 

# appsflyer_android_transformed["trial_starts_total_unique"] = appsflyer_android_transformed["af_purchase_unique"] + appsflyer_android_transformed["af_start_trial_unique"]
# appsflyer_android_transformed["trial_starts_total_all"] = appsflyer_android_transformed["af_purchase_all"] + appsflyer_android_transformed["af_start_trial_all"]

appsflyer_android_grouped = appsflyer_android_transformed.groupby(["date","advertiser"],as_index=False).sum()

appsflyer_android_grouped_final = appsflyer_android_grouped.loc[appsflyer_android_grouped["advertiser"].isin(paid_acquisition_advertisers), :]

appsflyer_android_grouped_final.tail()

,date,advertiser,installs,sessions,new_workout_saved_unique,af_purchase_unique,af_purchase_all,af_start_trial_unique,af_start_trial_all,trial_starts_unique,trial_starts_all,ltv_subs_unique,ltv_subs_all,ltv_subs_revenue
168,2019-05-04,pinterest_int,229,947,134,0,0,11,11,11,11,0,0,0.0
169,2019-05-05,Facebook Ads,14,58,3,0,0,0,0,0,0,0,0,0.0
170,2019-05-05,Facebook Ads EG,276,1109,151,1,1,19,19,20,20,0,0,0.0
171,2019-05-05,Organic,171,0,70,0,0,7,8,7,8,0,0,0.0
174,2019-05-05,pinterest_int,274,1082,168,0,0,7,7,7,7,0,0,0.0

### Create Placeholders for Organic, ASA (Basic and Advanced) DataFrame with Spend, Impressions, Clicks, etc.

In [17]:
# ORGANIC IOS
organic_spend_reach_clicks_ios = appsflyer_ios_grouped_final.loc[appsflyer_ios_grouped_final['advertiser'] == "Organic", ["date", "advertiser"]]
organic_spend_reach_clicks_ios["device_type"] = "IOS"
display(organic_spend_reach_clicks_ios.head())


# APPLE SEARCH BASIC IOS
asa_basic_spend_reach_clicks_ios = appsflyer_ios_grouped_final.loc[appsflyer_ios_grouped_final['advertiser'] == asa_basic_string, ["date", "advertiser"]]
asa_basic_spend_reach_clicks_ios["device_type"] = "IOS"
display(asa_basic_spend_reach_clicks_ios.head())

# APPLE SEARCH ADVANCED IOS
asa_advanced_spend_reach_clicks_ios = appsflyer_ios_grouped_final.loc[appsflyer_ios_grouped_final['advertiser'] == asa_advanced_string, ["date", "advertiser"]]
asa_advanced_spend_reach_clicks_ios["device_type"] = "IOS"
display(asa_advanced_spend_reach_clicks_ios.head())


# ORGANIC ANDROID
organic_spend_reach_clicks_android = appsflyer_android_grouped_final.loc[appsflyer_android_grouped_final['advertiser'] == "Organic", ["date", "advertiser"]]
organic_spend_reach_clicks_android["device_type"] = "ANDROID"
display(organic_spend_reach_clicks_android.head())

          date advertiser device_type
5   2019-04-06    Organic         IOS
14  2019-04-07    Organic         IOS
24  2019-04-08    Organic         IOS
34  2019-04-09    Organic         IOS
43  2019-04-10    Organic         IOS

          date advertiser device_type
1   2019-04-06  ASA Basic         IOS
10  2019-04-07  ASA Basic         IOS
20  2019-04-08  ASA Basic         IOS
30  2019-04-09  ASA Basic         IOS
39  2019-04-10  ASA Basic         IOS

          date    advertiser device_type
0   2019-04-06  ASA Advanced         IOS
9   2019-04-07  ASA Advanced         IOS
19  2019-04-08  ASA Advanced         IOS
29  2019-04-09  ASA Advanced         IOS
38  2019-04-10  ASA Advanced         IOS

          date advertiser device_type
1   2019-04-06    Organic     ANDROID
6   2019-04-07    Organic     ANDROID
12  2019-04-08    Organic     ANDROID
17  2019-04-09    Organic     ANDROID
24  2019-04-10    Organic     ANDROID

# COMBINE APPSFLYER AND ADVERTISER DATA TOGETHER

### IOS Combination

In [24]:
# facebook_spend_reach_clicks_ios
# pinterest_spend_reach_clicks_ios
# google_spend_reach_clicks_ios
# asa_basic_spend_reach_clicks_ios
# asa_advanced_spend_reach_clicks_ios
# organic_spend_reach_clicks_ios
# appsflyer_ios_grouped_final

advertisers_spend_reach_clicks_ios = pd.concat([facebook_spend_reach_clicks_ios, 
                                                pinterest_spend_reach_clicks_ios, 
                                                google_spend_reach_clicks_ios, 
                                                asa_basic_spend_reach_clicks_ios, 
                                                asa_advanced_spend_reach_clicks_ios, 
                                                organic_spend_reach_clicks_ios      ], 
                                               ignore_index=True, sort=False).sort_values(by=['date'])

merge_table_ios = pd.merge(advertisers_spend_reach_clicks_ios, appsflyer_ios_grouped_final, on=["date","advertiser"], how="left")
# merge_table_ios = pd.merge(advertisers_spend_reach_clicks_ios, appsflyer_ios_grouped_final, on=["date","advertiser"], how="outer")

display(merge_table_ios.head())


merge_table_ios.to_csv(folder_output_csvs + "/merged_IOS_data.csv", index=False, header=True)

,date,device_type,advertiser,spend,impressions,impressions_unique,clicks,clicks_unique,views,installs,...,new_workout_saved_unique,af_purchase_unique,af_purchase_all,af_start_trial_unique,af_start_trial_all,trial_starts_unique,trial_starts_all,ltv_subs_unique,ltv_subs_all,ltv_subs_revenue
0,2019-04-06,IOS,Facebook Ads,489.48,115877.0,112233.0,826.0,822.0,NaN,655,...,377,51,51,0,0,51,51,21,21,859.79
1,2019-04-06,IOS,Facebook Ads EG,497.64,85205.0,82800.0,772.0,766.0,NaN,0,...,0,0,0,0,0,0,0,0,0,0.00
2,2019-04-06,IOS,pinterest_int,652.34,744777.0,477859.0,4290.0,4196.0,NaN,598,...,365,26,26,1,1,27,27,11,11,509.89
3,2019-04-06,IOS,Organic,NaN,NaN,NaN,NaN,NaN,NaN,709,...,345,27,31,0,0,27,31,0,0,0.00
4,2019-04-06,IOS,ASA Basic,NaN,NaN,NaN,NaN,NaN,NaN,40,...,32,0,0,0,0,0,0,0,0,0.00

### ANDROID Combination

In [25]:
facebook_spend_reach_clicks_android.head()
pinterest_spend_reach_clicks_android.head()
appsflyer_android_grouped_final.head()


advertisers_spend_reach_clicks_android = pd.concat([facebook_spend_reach_clicks_android, pinterest_spend_reach_clicks_android, organic_spend_reach_clicks_android], ignore_index=True, sort=False).sort_values(by=['date'])

merge_table_android = pd.merge(advertisers_spend_reach_clicks_android, appsflyer_android_grouped_final, on=["date","advertiser"], how="left")
# merge_table_android = pd.merge(advertisers_spend_reach_clicks_android, appsflyer_android_grouped_final, on=["date","advertiser"], how="outer")

display(merge_table_android.head())

merge_table_android.to_csv(folder_output_csvs + "/merged_ANDROID_data.csv", index=False, header=True)

,date,device_type,advertiser,spend,impressions,impressions_unique,clicks,clicks_unique,installs,sessions,new_workout_saved_unique,af_purchase_unique,af_purchase_all,af_start_trial_unique,af_start_trial_all,trial_starts_unique,trial_starts_all,ltv_subs_unique,ltv_subs_all,ltv_subs_revenue
0,2019-04-06,ANDROID,Facebook Ads,500.83,65586.0,64112.0,1065.0,1058.0,398,1992,216,16,17,1,1,17,18,3,3,139.96
1,2019-04-06,ANDROID,Organic,NaN,NaN,NaN,NaN,NaN,124,0,63,6,6,0,0,6,6,0,0,0.00
2,2019-04-06,ANDROID,pinterest_int,150.00,162507.0,101204.0,1107.0,1092.0,188,967,121,7,8,0,0,7,8,1,1,9.99
3,2019-04-07,ANDROID,Facebook Ads,503.05,77194.0,74368.0,1327.0,1318.0,499,3406,311,31,33,1,1,32,34,16,16,659.84
4,2019-04-07,ANDROID,Organic,NaN,NaN,NaN,NaN,NaN,242,0,145,11,13,0,0,11,13,0,0,0.00

# CREATE AARRR DASHBOARD showing AGGREGATE DATA OVER DATE RANGE

In [26]:
### Date Range
start_date = "2019-05-05"
end_date = "2019-05-05"

columns_to_keep = ["date", "device_type", "advertiser", "spend", "installs", "trial_starts_unique"]

### IOS Aggregate Data

In [31]:
ios_aarrr = merge_table_ios.loc[(merge_table_ios["date"] >= start_date) 
                                        & 
                                        (merge_table_ios["date"] <= end_date), columns_to_keep]\
                                        .groupby(["advertiser"],as_index=False).sum()

display(ios_aarrr.head(20))

ios_aarrr.to_csv(folder_output_csvs + "/ios_aarrr_" + start_date + "_to_" + end_date + ".csv", index=False, header=True)

          advertiser    spend  installs  trial_starts_unique
0       ASA Advanced     0.00       132                   10
1          ASA Basic     0.00       303                   23
2       Facebook Ads  2292.11       719                   35
3    Facebook Ads EG  6446.19      2827                  342
4            Organic     0.00      6481                  355
5  googleadwords_int  3406.27      1844                   63
6      pinterest_int  5990.49      7187                  445

### Android Aggregate Data

In [28]:
android_aarrr = merge_table_android.loc[(merge_table_android["date"] >= start_date) 
                                        & 
                                        (merge_table_android["date"] <= end_date), columns_to_keep]\
                                        .groupby(["advertiser"],as_index=False).sum()

android_aarrr.head(100)

android_aarrr.to_csv(folder_output_csvs + "/android_aarrr_" + start_date + "_to_" + end_date + ".csv", index=False, header=True)